# Generated by Django 4.2.23 on 2025-07-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes', to='authentification.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=10, unique=True)),
                ('categorie', models.CharField(max_length=10)),
                ('horaires', models.TimeField()),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='todo.liste')),
            ],
        ),
    ]
