# Generated by Django 4.2.23 on 2025-07-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='mot_de_passe',
            new_name='password',
        ),
    ]
